name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Test Sylve
    steps:
      - uses: actions/checkout@v4

      - name: Build
        id: build
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          prepare: |
            pkg install -y node24 npm-node24 go

          run: |
            export GOPATH=$HOME/go
            export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

            echo "Environment Check:"
            go version
            node -v

            chmod +x scripts/build-deps-check.sh
            make
